// Code generated by scripts/generate-memory-event-registry.mjs. DO NOT EDIT.
package memory

import "fmt"

// Event source names shared across frontend/backend emitters.
const (
	SourceGenerate = "generate"
	SourceChat = "chat"
	SourceWorkspace = "workspace"
	SourceMCQ = "mcq"
	SourceMemory = "memory"
	SourceSystem = "system"
)

// Event type names approved in docs/memory-event-naming-guide-v0.md.
const (
	TypeIntakeStarted = "intake_started"
	TypeClarifyingQuestionsAnswered = "clarifying_questions_answered"
	TypeProblemGenerated = "problem_generated"
	TypeMCQSetGenerated = "mcq_set_generated"
	TypeInterviewPromptGenerated = "interview_prompt_generated"
	TypeGenerationFailed = "generation_failed"
	TypeThreadOpened = "thread_opened"
	TypeMessageSent = "message_sent"
	TypeAssistantReplied = "assistant_replied"
	TypeThreadClosed = "thread_closed"
	TypeProblemOpened = "problem_opened"
	TypeAttemptStarted = "attempt_started"
	TypeTestsRun = "tests_run"
	TypeHintRevealed = "hint_revealed"
	TypeAttemptSubmitted = "attempt_submitted"
	TypeAttemptSolved = "attempt_solved"
	TypeAttemptFailed = "attempt_failed"
	TypeSessionStarted = "session_started"
	TypeQuestionAnswered = "question_answered"
	TypeQuestionSkipped = "question_skipped"
	TypeFreeResponseEvaluated = "free_response_evaluated"
	TypeSessionCompleted = "session_completed"
	TypeSessionExited = "session_exited"
	TypeAnswerIncorrect = "answer_incorrect"
	TypeProfileViewed = "profile_viewed"
	TypeProfileRefreshed = "profile_refreshed"
	TypeNoteCreated = "note_created"
	TypeNoteUpdated = "note_updated"
	TypeNotePruned = "note_pruned"
	TypeWorkerProfileRefreshed = "worker_profile_refreshed"
	TypeMemoryAPIChecked = "memory_api_checked"
)

var allowedEventTypesBySource = map[string]map[string]struct{}{
	SourceGenerate: {
		TypeIntakeStarted: {},
		TypeClarifyingQuestionsAnswered: {},
		TypeProblemGenerated: {},
		TypeMCQSetGenerated: {},
		TypeInterviewPromptGenerated: {},
		TypeGenerationFailed: {},
	},
	SourceChat: {
		TypeThreadOpened: {},
		TypeMessageSent: {},
		TypeAssistantReplied: {},
		TypeThreadClosed: {},
	},
	SourceWorkspace: {
		TypeProblemOpened: {},
		TypeAttemptStarted: {},
		TypeTestsRun: {},
		TypeHintRevealed: {},
		TypeAttemptSubmitted: {},
		TypeAttemptSolved: {},
		TypeAttemptFailed: {},
	},
	SourceMCQ: {
		TypeSessionStarted: {},
		TypeQuestionAnswered: {},
		TypeQuestionSkipped: {},
		TypeFreeResponseEvaluated: {},
		TypeSessionCompleted: {},
		TypeSessionExited: {},
		TypeAnswerIncorrect: {},
	},
	SourceMemory: {
		TypeProfileViewed: {},
		TypeProfileRefreshed: {},
		TypeNoteCreated: {},
		TypeNoteUpdated: {},
		TypeNotePruned: {},
	},
	SourceSystem: {
		TypeWorkerProfileRefreshed: {},
		TypeMemoryAPIChecked: {},
	},
}

// ValidateEventName enforces the approved source/type registry for new writes.
func ValidateEventName(source, eventType string) error {
	typesForSource, ok := allowedEventTypesBySource[source]
	if !ok {
		return fmt.Errorf("unknown memory event source %q", source)
	}
	if _, ok := typesForSource[eventType]; !ok {
		return fmt.Errorf("unknown memory event type %q for source %q", eventType, source)
	}
	return nil
}
