// Code generated by scripts/generate-memory-event-registry.mjs. DO NOT EDIT.
import type { components } from './openapi';

export const memoryEventSources = {
  generate: 'generate',
  chat: 'chat',
  workspace: 'workspace',
  mcq: 'mcq',
  memory: 'memory',
  system: 'system',
} as const;

export type MemoryEventSource = (typeof memoryEventSources)[keyof typeof memoryEventSources];

export const memoryEventTypes = {
  intakeStarted: 'intake_started',
  clarifyingQuestionsAnswered: 'clarifying_questions_answered',
  problemGenerated: 'problem_generated',
  mcqSetGenerated: 'mcq_set_generated',
  interviewPromptGenerated: 'interview_prompt_generated',
  generationFailed: 'generation_failed',
  threadOpened: 'thread_opened',
  messageSent: 'message_sent',
  assistantReplied: 'assistant_replied',
  threadClosed: 'thread_closed',
  interviewStarted: 'interview_started',
  interviewCompleted: 'interview_completed',
  interviewExited: 'interview_exited',
  problemOpened: 'problem_opened',
  attemptStarted: 'attempt_started',
  testsRun: 'tests_run',
  hintRevealed: 'hint_revealed',
  attemptSubmitted: 'attempt_submitted',
  attemptSolved: 'attempt_solved',
  attemptFailed: 'attempt_failed',
  sessionStarted: 'session_started',
  questionAnswered: 'question_answered',
  questionSkipped: 'question_skipped',
  freeResponseEvaluated: 'free_response_evaluated',
  sessionCompleted: 'session_completed',
  sessionExited: 'session_exited',
  answerIncorrect: 'answer_incorrect',
  profileViewed: 'profile_viewed',
  profileRefreshed: 'profile_refreshed',
  noteCreated: 'note_created',
  noteUpdated: 'note_updated',
  notePruned: 'note_pruned',
  workerProfileRefreshed: 'worker_profile_refreshed',
  memoryApiChecked: 'memory_api_checked',

  // Compatibility aliases while callers migrate to guide-aligned names.
  problemRequested: 'intake_started',
  answerWrong: 'answer_incorrect',
  memoryNoteCreated: 'note_created',
} as const;

export type MemoryEventType = (typeof memoryEventTypes)[keyof typeof memoryEventTypes];
export type MemoryEventInput = components['schemas']['RecordMemoryEventInput'];
export type MemoryEventPayload = components['schemas']['JsonValue'];

interface BuildMemoryEventInput {
  type: MemoryEventType;
  summary: string;
  payload?: MemoryEventPayload;
  occurredAt?: string | Date;
}

function toOccurredAt(value?: string | Date) {
  if (!value) {
    return undefined;
  }

  return (value instanceof Date ? value : new Date(value)).toISOString();
}

function buildMemoryEvent(source: MemoryEventSource, input: BuildMemoryEventInput): MemoryEventInput {
  return {
    source,
    type: input.type,
    summary: input.summary,
    ...(input.payload === undefined ? {} : { payload: input.payload }),
    ...(toOccurredAt(input.occurredAt) ? { occurred_at: toOccurredAt(input.occurredAt) } : {}),
  };
}

export function buildGenerateEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.generate, input);
}

export function buildChatEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.chat, input);
}

export function buildWorkspaceEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.workspace, input);
}

export function buildMcqEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.mcq, input);
}

export function buildMemorySourceEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.memory, input);
}

export function buildSystemEvent(input: BuildMemoryEventInput) {
  return buildMemoryEvent(memoryEventSources.system, input);
}
