/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check backend liveness. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's memory profile for the selected tenant. */
        get: operations["getMemoryProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List append-only memory events for the authenticated user and tenant. */
        get: operations["listMemoryEvents"];
        put?: never;
        /** Append a memory event for the authenticated user and tenant. */
        post: operations["recordMemoryEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @example unauthenticated */
            code: string;
            /** @example Missing bearer token. */
            message: string;
        };
        ErrorEnvelope: {
            data: null;
            error: components["schemas"]["ApiError"];
        };
        HealthEnvelope: {
            data: components["schemas"]["HealthStatus"];
            error: null;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        MemoryProfileEnvelope: {
            data: components["schemas"]["MemoryProfile"];
            error: null;
        };
        MemoryEventsEnvelope: {
            data: components["schemas"]["MemoryEvent"][];
            error: null;
        };
        MemoryEventEnvelope: {
            data: components["schemas"]["MemoryEvent"];
            error: null;
        };
        MemoryProfile: {
            summary: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            next_review_at: string;
            strengths: string[];
            growth_edges: string[];
            skills: components["schemas"]["SkillProficiency"][];
            notes: components["schemas"]["MemoryNote"][];
        };
        SkillProficiency: {
            id: string;
            label: string;
            area: string;
            level: number;
            confidence: number;
            /** @enum {string} */
            trend: "up" | "flat" | "down";
            /** Format: date-time */
            last_practiced: string;
        };
        MemoryNote: {
            id: string;
            problem_id: string;
            title: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
            tags: string[];
            /** @enum {string} */
            action: "keep" | "review" | "prune";
        };
        MemoryEvent: {
            /** @example mem_evt_0123456789abcdef */
            id: string;
            tenant_id: string;
            user_id: string;
            /** @example chat */
            source: string;
            /** @example memory_note_created */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            created_at: string;
        };
        RecordMemoryEventInput: {
            /** @example generate */
            source: string;
            /** @example problem_generated */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /**
             * Format: date-time
             * @description Defaults to server time when omitted or zero.
             */
            occurred_at?: string;
        };
        JsonValue: {
            [key: string]: components["schemas"]["JsonValue"];
        } | components["schemas"]["JsonValue"][] | string | number | boolean | null;
    };
    responses: {
        /** @description Request body is invalid or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing, malformed, or rejected bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated user does not have access to the requested tenant. */
        TenantForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Backend failed while processing the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Optional tenant override. If omitted, the backend uses the authenticated principal's default tenant. */
        TenantHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    getMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant override. If omitted, the backend uses the authenticated principal's default tenant. */
                "X-CodeGym-Tenant-ID"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory profile loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["TenantForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listMemoryEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant override. If omitted, the backend uses the authenticated principal's default tenant. */
                "X-CodeGym-Tenant-ID"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory events loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventsEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["TenantForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    recordMemoryEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional tenant override. If omitted, the backend uses the authenticated principal's default tenant. */
                "X-CodeGym-Tenant-ID"?: components["parameters"]["TenantHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMemoryEventInput"];
            };
        };
        responses: {
            /** @description Memory event recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["TenantForbidden"];
        };
    };
}
