/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check backend liveness. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check backend readiness.
         * @description Returns success in in-memory mode. When Postgres is configured through NEON_CONNECTION_STRING or DATABASE_URL, this endpoint verifies database connectivity and returns 503 if the dependency is unavailable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's account profile. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user's editable account profile. */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/api/v1/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate GenAI token usage and estimated USD cost for the authenticated workspace user.
         * @description Totals tokens_in / tokens_out and estimated cost from recorded generation
         *     calls (MCQ generation, memory profile synthesis, etc.). Costs use a built-in rate
         *     card (USD per million tokens) last reviewed 2026-07-15 for Meta Muse Spark,
         *     Azure/OpenAI GPT-5.6 Terra family, and Gemini Flash-class models.
         */
        get: operations["getGenAICost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's memory profile for the selected workspace scope. */
        get: operations["getMemoryProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize and persist the authenticated user's memory profile from deterministic event evidence. */
        post: operations["refreshMemoryProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List append-only memory events for the authenticated user and workspace scope.
         * @description Returns events newest-first by occurrence time. All timestamps include an explicit UTC offset.
         */
        get: operations["listMemoryEvents"];
        put?: never;
        /** Append a memory event for the authenticated user and workspace scope. */
        post: operations["recordMemoryEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List practice sessions for the authenticated user and workspace scope.
         * @description Returns history summaries only; state snapshots and draft files are excluded.
         */
        get: operations["listSessions"];
        put?: never;
        /** Create a resumable practice session. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** Get one practice session for resume. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a practice session title, status, or resume state. */
        patch: operations["updateSession"];
        trace?: never;
    };
    "/api/v1/sessions/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Batch upsert draft files for a workspace session. */
        put: operations["upsertSessionFiles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find chat threads within the authenticated workspace-user scope. */
        get: operations["listChatThreads"];
        put?: never;
        /**
         * Create or resume a scoped interview or contextual-coach thread.
         * @description The server resolves authoritative session, problem, question, and memory context; clients never send DOM, source files, or hidden tests.
         */
        post: operations["createOrResumeChatThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        /** Restore the append-only transcript for one scoped thread. */
        get: operations["listChatMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append one idempotent user message and stream the assistant reply.
         * @description Emits versioned `meta`, `delta`, `complete`, and retryable `error` SSE events. Reusing client_message_id replays an already completed reply without duplicating the user message.
         */
        post: operations["streamChatTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the current thread and create a clean successor. */
        post: operations["resetChatThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete an interview and persist a validated coarse assessment event.
         * @description Completion remains durable when best-effort memory maintenance fails.
         */
        post: operations["finishInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{id}/exit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a compact exit event while leaving the interview resumable. */
        post: operations["exitInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a durable deterministic progress operation.
         * @description Seeds backend-owned queued steps for MCQ generation, memory reflection, or the ordered next-round reflection-plus-generation workflow. The operation is scoped to the authenticated user and workspace.
         */
        post: operations["createWorkflowOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-operations/{id}/events": {
        parameters: {
            query?: {
                /** @description Query cursor equivalent to Last-Event-ID, primarily for clients that cannot set the header. */
                after?: number;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
                /** @description Last applied monotonic sequence; already-seen events are not replayed. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["WorkflowOperationID"];
            };
            cookie?: never;
        };
        /**
         * Replay and follow ordered progress events for one scoped operation.
         * @description Emits `progress` SSE events with an `id` equal to the event sequence. The stream closes after the terminal event or client disconnect. Events report observable product steps only—never model reasoning, prompts, private records, source code, secrets, or stack traces.
         */
        get: operations["streamWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow-operations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["WorkflowOperationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the current observable step and operation as cancelled. */
        post: operations["cancelWorkflowOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the seeded public coding-problem catalog. */
        get: operations["listProblems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get one public coding-problem specification.
         * @description Hidden tests, the execution entrypoint, and the reference solution are never returned.
         */
        get: operations["getProblem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{id}/skeleton": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get editable starter files for one coding problem. */
        get: operations["getProblemSkeleton"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a problem solution against server-only tests in Daytona.
         * @description The backend loads the hidden tests and execution entrypoint from the problem catalog. Clients send only editable solution files.
         */
        post: operations["submitProblemSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Poll one structured coding-problem submission. */
        get: operations["getProblemSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated workspace's raw execution runs. */
        get: operations["listExecutions"];
        put?: never;
        /** Run an explicit file bundle in Daytona. */
        post: operations["createExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one raw execution run. */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-intakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restore unfinished topic baselines in most-recently-updated order. */
        get: operations["listPendingPracticeIntakes"];
        put?: never;
        /** Prepare, resume, or explicitly restart the self-reported baseline for a normalized topic. */
        post: operations["preparePracticeIntake"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-intakes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save partial answers immediately or mark an intake completed or skipped. */
        patch: operations["updatePracticeIntake"];
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate validated MCQ or persisted coding practice personalized by the caller's memory profile. */
        post: operations["generateContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcq/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade one short free-response practice answer with the configured AI evaluator. */
        post: operations["evaluateMCQFreeResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile/maintain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run structured LLM profile synthesis after a completed practice set.
         * @description Interprets bounded deterministic event evidence into the summary, strengths, growth edges, skills, and durable notes used by subsequent generation.
         */
        post: operations["maintainMemoryProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/notes/maintain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compatibility alias for full memory profile maintenance.
         * @deprecated
         */
        post: operations["maintainMemoryNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @example unauthenticated */
            code: string;
            /** @example Missing bearer token. */
            message: string;
        };
        ErrorEnvelope: {
            data: null;
            error: components["schemas"]["ApiError"];
        };
        HealthEnvelope: {
            data: components["schemas"]["HealthStatus"];
            error: null;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        ReadinessEnvelope: {
            data: components["schemas"]["ReadinessStatus"];
            error: null;
        };
        ReadinessStatus: {
            /** @example ok */
            status: string;
            /**
             * @example postgres
             * @enum {string}
             */
            mode: "memory" | "postgres";
        };
        UserProfileEnvelope: {
            data: components["schemas"]["UserProfile"];
            error: null;
        };
        CostAggregateEnvelope: {
            data: components["schemas"]["CostAggregate"];
            error: null;
        };
        CostAggregate: {
            /** @example USD */
            currency: string;
            /** @example 2026-07-15 */
            pricing_as_of: string;
            /** Format: int64 */
            total_tokens_in: number;
            /** Format: int64 */
            total_tokens_out: number;
            /** Format: double */
            total_cost_usd: number;
            call_count: number;
            by_provider: components["schemas"]["CostProviderSlice"][];
            by_model: components["schemas"]["CostModelSlice"][];
            rates: components["schemas"]["CostRate"][];
        };
        CostProviderSlice: {
            provider: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            /** Format: double */
            cost_usd: number;
            call_count: number;
        };
        CostModelSlice: {
            provider: string;
            model: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            /** Format: double */
            cost_usd: number;
            call_count: number;
        };
        CostRate: {
            provider: string;
            model_match?: string;
            /** Format: double */
            input_usd_per_mtok: number;
            /** Format: double */
            output_usd_per_mtok: number;
            source?: string;
        };
        UserProfile: {
            /** @example auth0|user_123 */
            user_id: string;
            /** @example kevin@example.com */
            email: string;
            /** @example Kevin Chen */
            display_name: string;
            /**
             * @description Where the current display name came from. `oauth` is seeded from the Auth0/Google name claim; `user` means the Settings page saved a manual override; `fallback` means no provider name was available.
             * @enum {string}
             */
            display_name_source: "oauth" | "user" | "fallback";
            /**
             * @description Internal default personal workspace ID.
             * @example personal-auth0-user-123
             */
            default_workspace_id: string;
        };
        UpdateUserProfileInput: {
            /** @example Kevin Chen */
            display_name: string;
        };
        MemoryProfileEnvelope: {
            data: components["schemas"]["MemoryProfile"];
            error: null;
        };
        MemoryEventsEnvelope: {
            data: components["schemas"]["MemoryEvent"][];
            error: null;
        };
        MemoryEventEnvelope: {
            data: components["schemas"]["MemoryEvent"];
            error: null;
        };
        SessionSummariesEnvelope: {
            data: components["schemas"]["SessionSummary"][];
            error: null;
        };
        SessionEnvelope: {
            data: components["schemas"]["Session"];
            error: null;
        };
        MemoryProfile: {
            summary: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            next_review_at: string;
            strengths: string[];
            growth_edges: string[];
            skills: components["schemas"]["SkillProficiency"][];
            notes: components["schemas"]["MemoryNote"][];
            provenance?: components["schemas"]["MemoryProfileProvenance"];
        };
        MemoryProfileProvenance: {
            schema_version: number;
            /** @enum {string} */
            trigger: "manual" | "daily" | "set-completion";
            provider: string;
            model: string;
            /** Format: date-time */
            synthesized_at: string;
            /** Format: date-time */
            evidence_through: string;
            event_count: number;
            /** @description Stable digest of filtered profile evidence. Unchanged daily ticks skip the model call when this digest still matches. */
            evidence_digest?: string;
        };
        SkillProficiency: {
            id: string;
            label: string;
            area: string;
            level: number;
            confidence: number;
            /** @enum {string} */
            trend: "up" | "flat" | "down";
            /** Format: date-time */
            last_practiced: string;
        };
        MemoryNote: {
            id: string;
            problem_id: string;
            title: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
            tags: string[];
            /** @enum {string} */
            action: "keep" | "review" | "prune";
        };
        MemoryEvent: {
            /** @example mem_evt_0123456789abcdef */
            id: string;
            /** @description Personal workspace scope ID. */
            workspace_id: string;
            user_id: string;
            /** @example memory */
            source: string;
            /** @example note_created */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /**
             * Format: date-time
             * @description Actual event occurrence time, serialized with an explicit UTC offset.
             */
            occurred_at: string;
            /**
             * Format: date-time
             * @description Persistence time, serialized with an explicit UTC offset.
             */
            created_at: string;
        };
        RecordMemoryEventInput: {
            /** @example generate */
            source: string;
            /** @example problem_generated */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /**
             * Format: date-time
             * @description Defaults to server time when omitted or zero.
             */
            occurred_at?: string;
        };
        /** @enum {string} */
        SessionKind: "workspace" | "mcq" | "interview";
        /** @enum {string} */
        SessionStatus: "active" | "completed" | "abandoned";
        SessionSummary: {
            /** @example sess_0123456789abcdef */
            id: string;
            /** @description Personal workspace scope ID. */
            workspace_id: string;
            user_id: string;
            kind: components["schemas"]["SessionKind"];
            status: components["schemas"]["SessionStatus"];
            title: string;
            problem_id?: string;
            generation_job_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_activity_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Session: components["schemas"]["SessionSummary"] & {
            state: components["schemas"]["JsonValue"];
            files?: components["schemas"]["SessionFile"][];
        };
        SessionFile: {
            /** @example main.go */
            file_path: string;
            content: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSessionInput: {
            kind: components["schemas"]["SessionKind"];
            title?: string;
            problem_id?: string;
            generation_job_id?: string;
            state?: components["schemas"]["JsonValue"];
        };
        UpdateSessionInput: {
            title?: string;
            status?: components["schemas"]["SessionStatus"];
            state?: components["schemas"]["JsonValue"];
        };
        UpsertSessionFilesInput: {
            files: {
                file_path: string;
                content: string;
            }[];
        };
        /** @enum {string} */
        ChatKind: "interview" | "coach";
        /** @enum {string} */
        ChatThreadStatus: "active" | "closed" | "completed";
        /** @enum {string} */
        ChatMessageStatus: "complete" | "interrupted";
        /** @enum {string} */
        InterviewMode: "coding" | "system_design" | "behavioral" | "open_coaching";
        ChatContextEnvelope: {
            /** @enum {integer} */
            version: 1;
            session_id: string;
            problem_id?: string;
            question_id?: string;
        };
        ChatThread: {
            id: string;
            workspace_id: string;
            user_id: string;
            session_id: string;
            kind: components["schemas"]["ChatKind"];
            mode?: components["schemas"]["InterviewMode"];
            status: components["schemas"]["ChatThreadStatus"];
            context: components["schemas"]["ChatContextEnvelope"];
            successor_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            closed_at?: string;
        };
        ChatMessage: {
            id: string;
            thread_id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            status: components["schemas"]["ChatMessageStatus"];
            client_message_id?: string;
            reply_to_message_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        ChatThreadWithMessages: components["schemas"]["ChatThread"] & {
            messages: components["schemas"]["ChatMessage"][];
        };
        CreateChatThreadInput: {
            kind: components["schemas"]["ChatKind"];
            mode?: components["schemas"]["InterviewMode"];
            session_id: string;
            question_id?: string;
        };
        ChatTurnInput: {
            client_message_id: string;
            message: string;
        };
        InterviewAssessment: {
            strengths: string[];
            growth_edges: string[];
            topic: string;
            mode: components["schemas"]["InterviewMode"];
            turn_count: number;
            duration_seconds: number;
        };
        InterviewFinishResult: {
            thread: components["schemas"]["ChatThread"];
            assessment: components["schemas"]["InterviewAssessment"];
            /** @enum {string} */
            memory_update_status: "synced" | "failed";
        };
        ChatThreadWithMessagesEnvelope: {
            data: components["schemas"]["ChatThreadWithMessages"];
            error: null;
        };
        ChatThreadEnvelope: {
            data: {
                thread: components["schemas"]["ChatThread"];
            };
            error: null;
        };
        ChatThreadListEnvelope: {
            data: {
                threads: components["schemas"]["ChatThread"][];
            };
            error: null;
        };
        ChatMessagesEnvelope: {
            data: {
                messages: components["schemas"]["ChatMessage"][];
            };
            error: null;
        };
        InterviewFinishEnvelope: {
            data: components["schemas"]["InterviewFinishResult"];
            error: null;
        };
        ProblemSummary: {
            /** @example two-sum */
            id: string;
            /** @example Two Sum */
            title: string;
            /** @example algorithms */
            category: string;
            /** @example python */
            language: string;
            framework?: string;
            /** @example 1 */
            difficulty: number;
            tags: string[];
            /** @example 15 */
            estimated_minutes: number;
            /** @example coding */
            type: string;
        };
        Problem: components["schemas"]["ProblemSummary"] & {
            /** @example 1 */
            version: string;
            description: string;
            subcategory?: string;
            runtime: components["schemas"]["ProblemRuntime"];
            files: components["schemas"]["ProblemFileManifest"];
            test_config: components["schemas"]["ProblemTestConfig"];
            hints?: components["schemas"]["ProblemHint"][];
        };
        ProblemRuntime: {
            /** @example python:3.13 */
            image: string;
            /** @example 20 */
            timeout_seconds: number;
            /** @example 256 */
            memory_mb: number;
            /** @enum {string} */
            network_mode: "block-all";
        };
        ProblemFileManifest: {
            skeleton: components["schemas"]["ProblemFileRef"][];
        };
        ProblemFileRef: {
            /** @example solution.py */
            path: string;
            entry?: boolean;
            readonly?: boolean;
        };
        ProblemTestConfig: {
            /** @enum {string} */
            strategy: "unit" | "http";
            comparator: components["schemas"]["AcceptanceComparator"];
            /** @description HTTP server readiness deadline in seconds; defaults to 10 for the http strategy. */
            readiness_timeout_seconds?: number;
        };
        AcceptanceComparator: {
            /** @enum {string} */
            kind: "exact" | "set" | "multiset" | "sorted" | "float" | "checker";
            /** @description Numeric tolerance for the float comparator; defaults to 1e-6. */
            epsilon?: number;
        };
        ProblemHint: {
            cost: number;
            text: string;
        };
        SubmissionFile: {
            /** @example solution.py */
            path: string;
            content: string;
        };
        ProblemSkeleton: {
            files: components["schemas"]["SubmissionFile"][];
        };
        ProblemList: {
            problems: components["schemas"]["ProblemSummary"][];
            total: number;
        };
        ProblemListEnvelope: {
            data: components["schemas"]["ProblemList"];
            error: null;
        };
        ProblemEnvelope: {
            data: components["schemas"]["Problem"];
            error: null;
        };
        ProblemSkeletonEnvelope: {
            data: components["schemas"]["ProblemSkeleton"];
            error: null;
        };
        SubmitProblemInput: {
            /** @example two-sum */
            problem_id: string;
            /** @example sess_0123456789abcdef */
            session_id?: string;
            files: components["schemas"]["SubmissionFile"][];
        };
        SubmissionAccepted: {
            /** @example exec_run_0123456789abcdef */
            submission_id: string;
            /**
             * @description Best-effort profile maintenance outcome. The submission result is durable even when this is failed.
             * @enum {string}
             */
            memory_update_status?: "synced" | "failed";
        };
        SubmissionAcceptedEnvelope: {
            data: components["schemas"]["SubmissionAccepted"];
            error: null;
        };
        /** @enum {string} */
        SubmissionStatus: "pending" | "running" | "completed" | "timeout" | "out_of_memory" | "crashed" | "error";
        Submission: {
            status: components["schemas"]["SubmissionStatus"];
            result?: components["schemas"]["TestResult"];
            failure_detail?: string;
            /** @description Learner program stdout, captured separately from the judge verdict. */
            stdout: string;
            /** @description True when stdout or stderr exceeded the configured byte cap. */
            output_truncated: boolean;
        };
        TestResult: {
            /** @enum {string} */
            status: "pass" | "fail";
            total: number;
            passed: number;
            failed: number;
            /** Format: int64 */
            duration_ms: number;
            test_cases: components["schemas"]["TestCaseResult"][];
            compile_error?: string;
        };
        TestCaseResult: {
            name: string;
            /** @enum {string} */
            status: "pass" | "fail";
            /** Format: int64 */
            duration_ms: number;
            error?: string;
        };
        SubmissionEnvelope: {
            data: components["schemas"]["Submission"];
            error: null;
        };
        /** @enum {string} */
        ExecutionStatus: "queued" | "running" | "passed" | "failed" | "timeout" | "out_of_memory" | "crashed" | "error";
        ExecutionRun: {
            /** @example exec_run_0123456789abcdef */
            id: string;
            workspace_id: string;
            user_id: string;
            problem_id?: string;
            language: string;
            entrypoint: string;
            status: components["schemas"]["ExecutionStatus"];
            exit_code?: number;
            output: string;
            error?: string;
            /** Format: int64 */
            duration_ms: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        SubmitExecutionInput: {
            problem_id: string;
            language: string;
            entrypoint: string;
            files: components["schemas"]["SubmissionFile"][];
            limits: components["schemas"]["ExecutionLimits"];
        };
        ExecutionLimits: {
            timeout_seconds: number;
            memory_mb: number;
            /** @enum {string} */
            network_mode: "block-all";
        };
        ExecutionRunEnvelope: {
            data: components["schemas"]["ExecutionRun"];
            error: null;
        };
        ExecutionRunsEnvelope: {
            data: components["schemas"]["ExecutionRun"][];
            error: null;
        };
        GenerateInput: {
            /**
             * @description MCQ and problem are implemented; interview uses the chat API.
             * @enum {string}
             */
            kind: "mcq" | "problem" | "interview";
            spec?: components["schemas"]["MCQSpec"] | components["schemas"]["ProblemGenerationSpec"];
            /** @description Optional completed intake in the caller's workspace. Its self-report remains separate from demonstrated memory. */
            intake_id?: string;
            /** @description Optional scoped workflow operation receiving deterministic MCQ progress events. */
            operation_id?: string;
        };
        PreparePracticeIntakeInput: {
            /** @description Original user-entered practice topic. The server derives an exact normalized topic identity. */
            topic: string;
            /** @description Original New Practice choices retained for resume and generation context. */
            practice_seed?: {
                [key: string]: unknown;
            };
            /**
             * @description Creates a fresh pending intake even when this topic was previously completed or skipped.
             * @default false
             */
            restart: boolean;
        };
        UpdatePracticeIntakeInput: {
            /** @description Question ID to option ID updates; each supplied option is validated. */
            answers?: {
                [key: string]: string;
            };
            /** @enum {string} */
            status?: "pending" | "completed" | "skipped";
        };
        PracticeIntakeOption: {
            id: string;
            label: string;
        };
        PracticeIntakeQuestion: {
            id: string;
            dimension: string;
            text: string;
            options: components["schemas"]["PracticeIntakeOption"][];
        };
        PracticeIntake: {
            id: string;
            workspace_id: string;
            user_id: string;
            normalized_topic: string;
            original_topic: string;
            practice_seed: {
                [key: string]: unknown;
            };
            questions: components["schemas"]["PracticeIntakeQuestion"][];
            answers: {
                [key: string]: string;
            };
            /** @enum {string} */
            status: "pending" | "completed" | "skipped";
            suppression_reason?: string;
            generation_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        PracticeIntakeEnvelope: {
            data: components["schemas"]["PracticeIntake"];
            error: null;
        };
        PracticeIntakeListEnvelope: {
            data: components["schemas"]["PracticeIntake"][];
            error: null;
        };
        /** @description The model chooses single-select, multi-select, or free-response independently for each generated question. */
        MCQSpec: {
            /**
             * @description Coarse topic; empty spreads questions across growth edges.
             * @example hash tables
             */
            topic?: string;
            /**
             * @description The user's free-text "what do you want to study?" ask; steers concept selection together with memory notes.
             * @example I want to drill Go concurrency patterns
             */
            prompt?: string;
            /** @default 5 */
            count: number;
            /** @example medium */
            difficulty?: string;
            /** @description Round number in a continuous marathon; later rounds avoid repeating earlier questions. */
            round?: number;
        };
        MaintainProfileInput: {
            /**
             * @description Highlights the just-completed practice set inside the bounded cross-session evidence digest.
             * @example mcq_abc123_r2
             */
            session_id?: string;
            /** @description Optional scoped memory_reflection or mcq_next_round workflow operation. */
            operation_id?: string;
        };
        /** @enum {string} */
        WorkflowKind: "mcq_generation" | "memory_reflection" | "mcq_next_round" | "problem_generation";
        /** @enum {string} */
        WorkflowStatus: "queued" | "running" | "succeeded" | "failed";
        CreateWorkflowOperationInput: {
            kind: components["schemas"]["WorkflowKind"];
        };
        WorkflowOperation: {
            id: string;
            workspace_id: string;
            user_id: string;
            kind: components["schemas"]["WorkflowKind"];
            status: components["schemas"]["WorkflowStatus"];
            /** Format: int64 */
            last_sequence: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        WorkflowProgressEvent: {
            operation_id: string;
            /** Format: int64 */
            sequence: number;
            /** @description Stable backend-owned product step identifier. */
            step_id: string;
            /** @description Backend-owned user-facing product step label. */
            label: string;
            status: components["schemas"]["WorkflowStatus"];
            /** Format: date-time */
            timestamp: string;
            /** @description Allowlisted safe scalar metadata only. terminal=true identifies the final event. */
            metadata?: {
                [key: string]: string | number | boolean;
            };
        };
        WorkflowCreateResult: {
            operation: components["schemas"]["WorkflowOperation"];
            events: components["schemas"]["WorkflowProgressEvent"][];
        };
        WorkflowCreateEnvelope: {
            data: components["schemas"]["WorkflowCreateResult"];
            error: null;
        };
        WorkflowCancelResult: {
            operation: components["schemas"]["WorkflowOperation"];
            event: components["schemas"]["WorkflowProgressEvent"];
        };
        WorkflowCancelEnvelope: {
            data: components["schemas"]["WorkflowCancelResult"];
            error: null;
        };
        MCQQuestion: {
            /** @example mq1 */
            id: string;
            /** @enum {string} */
            type: "single_select" | "multi_select" | "free_response";
            text: string;
            /** @description Exactly four options for single-select and multi-select; omitted for free response. */
            options?: string[];
            /** @description Required only for single-select. */
            correctIndex?: number;
            /** @description Required only for multi-select; grading requires an exact set match. */
            correctIndices?: number[];
            /** @description Concise evaluator reference answer for free-response items. */
            expectedAnswer?: string;
            /** @description Objective binary grading criteria for free-response items. */
            rubric?: string;
            concept: string;
            helpContent: string;
        };
        FreeResponseEvaluationInput: {
            question_id?: string;
            question: string;
            concept?: string;
            expected_answer: string;
            rubric: string;
            answer: string;
        };
        FreeResponseEvaluation: {
            correct: boolean;
            feedback: string;
            provider?: string;
            model?: string;
        };
        FreeResponseEvaluationEnvelope: {
            data: components["schemas"]["FreeResponseEvaluation"];
            error: null;
        };
        GenerateMCQResult: {
            /** @example mcq */
            kind: string;
            questions: components["schemas"]["MCQQuestion"][];
            /** @example openai_compat */
            provider: string;
            /** @example anthropic/claude-haiku-4.5 */
            model: string;
        };
        GenerateMCQEnvelope: {
            data: components["schemas"]["GenerateMCQResult"];
            error: null;
        };
        ProblemGenerationSpec: {
            topic?: string;
            prompt?: string;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            /** @default python */
            language?: "python" | "go";
        };
        GenerateProblemResult: {
            /** @enum {string} */
            kind: "problem";
            problem_id: string;
            problem: components["schemas"]["Problem"];
            provider: string;
            model: string;
        };
        GenerateProblemEnvelope: {
            data: components["schemas"]["GenerateProblemResult"];
            error: null;
        };
        JsonValue: {
            [key: string]: components["schemas"]["JsonValue"];
        } | components["schemas"]["JsonValue"][] | string | number | boolean | null;
    };
    responses: {
        /** @description Request body is invalid or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing, malformed, or rejected bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated user does not have access to the requested workspace scope. */
        WorkspaceForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Requested resource was not found in the authenticated workspace scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Backend failed while processing the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
        WorkspaceHeader: string;
        SessionID: string;
        ChatThreadID: string;
        WorkflowOperationID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessEnvelope"];
                };
            };
            /** @description Backend dependencies are not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileInput"];
            };
        };
        responses: {
            /** @description User profile updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getGenAICost: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost aggregate loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostAggregateEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory profile loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory profile refreshed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listMemoryEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory events loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventsEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    recordMemoryEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMemoryEventInput"];
            };
        };
        responses: {
            /** @description Memory event recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                kind?: components["schemas"]["SessionKind"];
                status?: components["schemas"]["SessionStatus"];
                limit?: number;
                /** @description RFC3339 last_activity_at cursor; returns sessions before this timestamp. */
                cursor?: string;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session summaries loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummariesEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionInput"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail loaded. Workspace sessions include draft files. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionInput"];
            };
        };
        responses: {
            /** @description Session updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertSessionFiles: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSessionFilesInput"];
            };
        };
        responses: {
            /** @description Session files updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listChatThreads: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ChatKind"];
                status?: components["schemas"]["ChatThreadStatus"];
                session_id?: string;
                limit?: number;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching thread summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadListEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
        };
    };
    createOrResumeChatThread: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatThreadInput"];
            };
        };
        responses: {
            /** @description Active thread and its persisted transcript. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadWithMessagesEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
        };
    };
    listChatMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcript restored in creation order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessagesEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    streamChatTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnInput"];
            };
        };
        responses: {
            /** @description Server-sent event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    resetChatThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successor thread and opening transcript. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadWithMessagesEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    finishInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed interview, coarse assessment, and memory update status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewFinishEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exitInterview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ChatThreadID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active interview retained for resume. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createWorkflowOperation: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowOperationInput"];
            };
        };
        responses: {
            /** @description Scoped operation and its initial queued step events. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowCreateEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
        };
    };
    streamWorkflowEvents: {
        parameters: {
            query?: {
                /** @description Query cursor equivalent to Last-Event-ID, primarily for clients that cannot set the header. */
                after?: number;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
                /** @description Last applied monotonic sequence; already-seen events are not replayed. */
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["WorkflowOperationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent workflow event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelWorkflowOperation: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["WorkflowOperationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terminal failed operation and cancellation event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowCancelEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            /** @description The operation already reached a terminal state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listProblems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public problem summaries loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public problem specification loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getProblemSkeleton: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public starter files loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemSkeletonEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    submitProblemSolution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitProblemInput"];
            };
        };
        responses: {
            /** @description Submission accepted; poll the returned submission ID. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionAcceptedEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Daytona execution is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getProblemSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission status and, when complete, per-test results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listExecutions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution runs loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRunsEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createExecution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitExecutionInput"];
            };
        };
        responses: {
            /** @description Execution completed and persisted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRunEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Daytona execution is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution run loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionRunEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPendingPracticeIntakes: {
        parameters: {
            query?: {
                status?: "pending";
                limit?: number;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending practice intakes scoped to the authenticated workspace user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeIntakeListEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    preparePracticeIntake: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreparePracticeIntakeInput"];
            };
        };
        responses: {
            /** @description Existing suppression or pending state, or a newly generated intake. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeIntakeEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
            /** @description Practice intake is not configured on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updatePracticeIntake: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePracticeIntakeInput"];
            };
        };
        responses: {
            /** @description Updated workspace-scoped intake. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeIntakeEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            /** @description Practice intake is not configured on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generateContent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInput"];
            };
        };
        responses: {
            /** @description Content generated and validated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateMCQEnvelope"] | components["schemas"]["GenerateProblemEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            /** @description A saved terminal result has a retryable memory update that must finish before another coding problem is generated. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The requested generation kind is not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The model provider failed or returned unusable output after the retry budget. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Generation is not configured on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    evaluateMCQFreeResponse: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreeResponseEvaluationInput"];
            };
        };
        responses: {
            /** @description Binary correctness and concise evaluator feedback. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeResponseEvaluationEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            /** @description The evaluator provider failed or returned unusable output; the answer remains unconfirmed and retryable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description AI evaluation is not configured on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    maintainMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaintainProfileInput"];
            };
        };
        responses: {
            /** @description The latest successfully synthesized profile, or the preserved fallback profile when generation is unavailable or invalid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    maintainMemoryNotes: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaintainProfileInput"];
            };
        };
        responses: {
            /** @description Latest memory profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
}
