/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check backend liveness. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check backend readiness.
         * @description Returns success in in-memory mode. When Postgres is configured through NEON_CONNECTION_STRING or DATABASE_URL, this endpoint verifies database connectivity and returns 503 if the dependency is unavailable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's account profile. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user's editable account profile. */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/api/v1/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate GenAI token usage and estimated USD cost for the authenticated workspace user.
         * @description Totals tokens_in / tokens_out and estimated cost from recorded generation
         *     calls (MCQ generate, note maintenance, etc.). Costs use a built-in rate
         *     card (USD per million tokens) last reviewed 2026-07-15 for Meta Muse Spark,
         *     Azure/OpenAI GPT-5.6 Terra family, and Gemini Flash-class models.
         */
        get: operations["getGenAICost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's memory profile for the selected workspace scope. */
        get: operations["getMemoryProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize and persist the authenticated user's memory profile from deterministic event evidence. */
        post: operations["refreshMemoryProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List append-only memory events for the authenticated user and workspace scope.
         * @description Returns events newest-first by occurrence time. All timestamps include an explicit UTC offset.
         */
        get: operations["listMemoryEvents"];
        put?: never;
        /** Append a memory event for the authenticated user and workspace scope. */
        post: operations["recordMemoryEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List practice sessions for the authenticated user and workspace scope.
         * @description Returns history summaries only; state snapshots and draft files are excluded.
         */
        get: operations["listSessions"];
        put?: never;
        /** Create a resumable practice session. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        /** Get one practice session for resume. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a practice session title, status, or resume state. */
        patch: operations["updateSession"];
        trace?: never;
    };
    "/api/v1/sessions/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        get?: never;
        /** Batch upsert draft files for a workspace session. */
        put: operations["upsertSessionFiles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate practice content (MCQ sets today; problems and interviews later) personalized by the caller's memory profile. */
        post: operations["generateContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/profile/maintain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run structured LLM profile synthesis after a completed practice set.
         * @description Interprets bounded deterministic event evidence into the summary, strengths, growth edges, skills, and durable notes used by subsequent generation.
         */
        post: operations["maintainMemoryProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/notes/maintain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compatibility alias for full memory profile maintenance.
         * @deprecated
         */
        post: operations["maintainMemoryNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /** @example unauthenticated */
            code: string;
            /** @example Missing bearer token. */
            message: string;
        };
        ErrorEnvelope: {
            data: null;
            error: components["schemas"]["ApiError"];
        };
        HealthEnvelope: {
            data: components["schemas"]["HealthStatus"];
            error: null;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
        };
        ReadinessEnvelope: {
            data: components["schemas"]["ReadinessStatus"];
            error: null;
        };
        ReadinessStatus: {
            /** @example ok */
            status: string;
            /**
             * @example postgres
             * @enum {string}
             */
            mode: "memory" | "postgres";
        };
        UserProfileEnvelope: {
            data: components["schemas"]["UserProfile"];
            error: null;
        };
        CostAggregateEnvelope: {
            data: components["schemas"]["CostAggregate"];
            error: null;
        };
        CostAggregate: {
            /** @example USD */
            currency: string;
            /** @example 2026-07-15 */
            pricing_as_of: string;
            /** Format: int64 */
            total_tokens_in: number;
            /** Format: int64 */
            total_tokens_out: number;
            /** Format: double */
            total_cost_usd: number;
            call_count: number;
            by_provider: components["schemas"]["CostProviderSlice"][];
            by_model: components["schemas"]["CostModelSlice"][];
            rates: components["schemas"]["CostRate"][];
        };
        CostProviderSlice: {
            provider: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            /** Format: double */
            cost_usd: number;
            call_count: number;
        };
        CostModelSlice: {
            provider: string;
            model: string;
            /** Format: int64 */
            tokens_in: number;
            /** Format: int64 */
            tokens_out: number;
            /** Format: double */
            cost_usd: number;
            call_count: number;
        };
        CostRate: {
            provider: string;
            model_match?: string;
            /** Format: double */
            input_usd_per_mtok: number;
            /** Format: double */
            output_usd_per_mtok: number;
            source?: string;
        };
        UserProfile: {
            /** @example auth0|user_123 */
            user_id: string;
            /** @example kevin@example.com */
            email: string;
            /** @example Kevin Chen */
            display_name: string;
            /**
             * @description Where the current display name came from. `oauth` is seeded from the Auth0/Google name claim; `user` means the Settings page saved a manual override; `fallback` means no provider name was available.
             * @enum {string}
             */
            display_name_source: "oauth" | "user" | "fallback";
            /**
             * @description Internal default personal workspace ID.
             * @example personal-auth0-user-123
             */
            default_workspace_id: string;
        };
        UpdateUserProfileInput: {
            /** @example Kevin Chen */
            display_name: string;
        };
        MemoryProfileEnvelope: {
            data: components["schemas"]["MemoryProfile"];
            error: null;
        };
        MemoryEventsEnvelope: {
            data: components["schemas"]["MemoryEvent"][];
            error: null;
        };
        MemoryEventEnvelope: {
            data: components["schemas"]["MemoryEvent"];
            error: null;
        };
        SessionSummariesEnvelope: {
            data: components["schemas"]["SessionSummary"][];
            error: null;
        };
        SessionEnvelope: {
            data: components["schemas"]["Session"];
            error: null;
        };
        MemoryProfile: {
            summary: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            next_review_at: string;
            strengths: string[];
            growth_edges: string[];
            skills: components["schemas"]["SkillProficiency"][];
            notes: components["schemas"]["MemoryNote"][];
            provenance?: components["schemas"]["MemoryProfileProvenance"];
        };
        MemoryProfileProvenance: {
            schema_version: number;
            /** @enum {string} */
            trigger: "manual" | "daily" | "set-completion";
            provider: string;
            model: string;
            /** Format: date-time */
            synthesized_at: string;
            /** Format: date-time */
            evidence_through: string;
            event_count: number;
        };
        SkillProficiency: {
            id: string;
            label: string;
            area: string;
            level: number;
            confidence: number;
            /** @enum {string} */
            trend: "up" | "flat" | "down";
            /** Format: date-time */
            last_practiced: string;
        };
        MemoryNote: {
            id: string;
            problem_id: string;
            title: string;
            summary: string;
            /** Format: date-time */
            created_at: string;
            tags: string[];
            /** @enum {string} */
            action: "keep" | "review" | "prune";
        };
        MemoryEvent: {
            /** @example mem_evt_0123456789abcdef */
            id: string;
            /** @description Personal workspace scope ID. */
            workspace_id: string;
            user_id: string;
            /** @example memory */
            source: string;
            /** @example note_created */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /**
             * Format: date-time
             * @description Actual event occurrence time, serialized with an explicit UTC offset.
             */
            occurred_at: string;
            /**
             * Format: date-time
             * @description Persistence time, serialized with an explicit UTC offset.
             */
            created_at: string;
        };
        RecordMemoryEventInput: {
            /** @example generate */
            source: string;
            /** @example problem_generated */
            type: string;
            summary: string;
            payload?: components["schemas"]["JsonValue"];
            /**
             * Format: date-time
             * @description Defaults to server time when omitted or zero.
             */
            occurred_at?: string;
        };
        /** @enum {string} */
        SessionKind: "workspace" | "mcq" | "interview";
        /** @enum {string} */
        SessionStatus: "active" | "completed" | "abandoned";
        SessionSummary: {
            /** @example sess_0123456789abcdef */
            id: string;
            /** @description Personal workspace scope ID. */
            workspace_id: string;
            user_id: string;
            kind: components["schemas"]["SessionKind"];
            status: components["schemas"]["SessionStatus"];
            title: string;
            problem_id?: string;
            generation_job_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_activity_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Session: components["schemas"]["SessionSummary"] & {
            state: components["schemas"]["JsonValue"];
            files?: components["schemas"]["SessionFile"][];
        };
        SessionFile: {
            /** @example main.go */
            file_path: string;
            content: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSessionInput: {
            kind: components["schemas"]["SessionKind"];
            title?: string;
            problem_id?: string;
            generation_job_id?: string;
            state?: components["schemas"]["JsonValue"];
        };
        UpdateSessionInput: {
            title?: string;
            status?: components["schemas"]["SessionStatus"];
            state?: components["schemas"]["JsonValue"];
        };
        UpsertSessionFilesInput: {
            files: {
                file_path: string;
                content: string;
            }[];
        };
        GenerateInput: {
            /**
             * @description Generation kind. Only "mcq" is implemented today.
             * @enum {string}
             */
            kind: "mcq" | "problem" | "interview";
            spec?: components["schemas"]["MCQSpec"];
        };
        MCQSpec: {
            /**
             * @description Coarse topic; empty spreads questions across growth edges.
             * @example hash tables
             */
            topic?: string;
            /**
             * @description The user's free-text "what do you want to study?" ask; steers concept selection together with memory notes.
             * @example I want to drill Go concurrency patterns
             */
            prompt?: string;
            /** @default 5 */
            count: number;
            /** @example medium */
            difficulty?: string;
            /** @description Round number in a continuous marathon; later rounds avoid repeating earlier questions. */
            round?: number;
        };
        MaintainProfileInput: {
            /**
             * @description Highlights the just-completed practice set inside the bounded cross-session evidence digest.
             * @example mcq_abc123_r2
             */
            session_id?: string;
        };
        MCQQuestion: {
            /** @example mq1 */
            id: string;
            text: string;
            options: string[];
            correctIndex: number;
            concept: string;
            helpContent: string;
        };
        GenerateMCQResult: {
            /** @example mcq */
            kind: string;
            questions: components["schemas"]["MCQQuestion"][];
            /** @example openai_compat */
            provider: string;
            /** @example anthropic/claude-haiku-4.5 */
            model: string;
        };
        GenerateMCQEnvelope: {
            data: components["schemas"]["GenerateMCQResult"];
            error: null;
        };
        JsonValue: {
            [key: string]: components["schemas"]["JsonValue"];
        } | components["schemas"]["JsonValue"][] | string | number | boolean | null;
    };
    responses: {
        /** @description Request body is invalid or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing, malformed, or rejected bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated user does not have access to the requested workspace scope. */
        WorkspaceForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Requested resource was not found in the authenticated workspace scope. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Backend failed while processing the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
        WorkspaceHeader: string;
        SessionID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessEnvelope"];
                };
            };
            /** @description Backend dependencies are not ready. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileInput"];
            };
        };
        responses: {
            /** @description User profile updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getGenAICost: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost aggregate loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostAggregateEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory profile loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory profile refreshed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listMemoryEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory events loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventsEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    recordMemoryEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordMemoryEventInput"];
            };
        };
        responses: {
            /** @description Memory event recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEventEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                kind?: components["schemas"]["SessionKind"];
                status?: components["schemas"]["SessionStatus"];
                limit?: number;
                /** @description RFC3339 last_activity_at cursor; returns sessions before this timestamp. */
                cursor?: string;
            };
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session summaries loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummariesEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionInput"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail loaded. Workspace sessions include draft files. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionInput"];
            };
        };
        responses: {
            /** @description Session updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertSessionFiles: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path: {
                id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSessionFilesInput"];
            };
        };
        responses: {
            /** @description Session files updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    generateContent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInput"];
            };
        };
        responses: {
            /** @description Content generated and validated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateMCQEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            /** @description The requested generation kind is not implemented yet. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The model provider failed or returned unusable output after the retry budget. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Generation is not configured on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    maintainMemoryProfile: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaintainProfileInput"];
            };
        };
        responses: {
            /** @description The latest successfully synthesized profile, or the preserved fallback profile when generation is unavailable or invalid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    maintainMemoryNotes: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional workspace-scope override. Product flows should normally omit it so the backend uses the authenticated principal's default personal workspace. The legacy header name X-CodeGym-Tenant-ID is still accepted by the server for compatibility. */
                "X-CodeGym-Workspace-ID"?: components["parameters"]["WorkspaceHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaintainProfileInput"];
            };
        };
        responses: {
            /** @description Latest memory profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["WorkspaceForbidden"];
            500: components["responses"]["InternalError"];
        };
    };
}
